const products = [
    {
        code: 1,
        name: 'Benegripe Cartela',
        pics: ["../../assets/images/products/Benegripe.jpg"],
        price: 8.90,
        stock: 20,
        brand: 'benegripe',
        category: 'antigripal',
        promotion: true,
        discount: 17,
    },
    {
        code: 2,
        name: 'Centrum complexo vitamínico',
        pics: ["../../assets/images/products/Centrum1.jpg"],
        price: 14.90,
        stock: 10,
        brand: 'Centrum',
        category: 'vitamina',
        promotion: true,
        discount: 10,
    },
    {
        code: 3,
        name: 'Centrum mulher complexo vitamínico',
        pics: ["../../assets/images/products/CentrumMulher.jpg"],
        price: 14.90,
        stock: 9,
        brand: 'Centrum',
        category: 'vitamina',
        promotion: true,
        discount: 10,
    },
    {
        code: 4,
        name: 'Hipoglós contra assaduras',
        pics: ["../../assets/images/products/Hipoglos.jpg"],
        price: 15.90,
        stock: 5,
        brand: 'Hipoglos',
        category: 'dorecontusao',
        promotion: false,
        discount: 0,
    },
    {
        code: 5,
        name: 'Naldecon dia e Noite Cartela',
        pics: ["../../assets/images/products/Naldecon.jpg"],
        price: 10.90,
        stock: 25,
        brand: 'Naldecon',
        category: 'antigripal',
        promotion: true,
        discount: 25,
    },
    {
        code: 6,
        name: 'Neosaldina contra dor de cabeça',
        pics: ["../../assets/images/products/Neosaldina.jpg"],
        price: 9.90,
        stock: 20,
        brand: 'Neosaldina',
        category: 'dorecontusao',
        promotion: false,
        discount: 0,
    },
    {
        code: 7,
        name: 'Redoxitos',
        pics: ["../../assets/images/products/Redoxitos.jpg"],
        price: 10.90,
        stock: 50,
        brand: 'Redoxitos',
        category: 'vitamina',
        promotion: true,
        discount: 20,
    },
    {
        code: 8,
        name: 'Resfenol',
        pics: ["../../assets/images/products/Resfenol.jpg"],
        price: 10.90,
        stock: 20,
        brand: 'Resfenol',
        category: 'antigripal',
        promotion: false,
        discount: 0,
    },
    {
        code: 9,
        name: 'Seringa 10ml',
        pics: ["../../assets/images/products/Seringa.jpg"],
        price: 5.90,
        stock: 20,
        brand: 'Descarpack',
        category: 'descartavel',
        promotion: false,
        discount: 0,
    },
    {
        code: 10,
        name: 'Soro Fisiológico 500ml',
        pics: ["../../assets/images/products/Soro.jpg"],
        price: 11.90,
        stock: 10,
        brand: 'adv farma',
        category: 'saude',
        promotion: false,
        discount: 0,
    }
]